drop table persona cascade;
drop table estudiante  cascade;
drop table direccion cascade;
drop table email cascade;
drop table empleado cascade;
drop table empresa cascade;
drop table paciente cascade;
drop table servicio cascade;
drop table telefono cascade;